### ISSUE TITLE
Problems with Slopes

### ISSUE THREAD

**Issue by Xeadriel** [TheSHEEEP/godotdetour#11]
Hey,

I was wondering if you could maybe help me out with this issue. I've heard navmeshes are not very good for several y levels but I'd like to hear an educated opinion for if there is a way for me to figure it out. Thanks for your time.

I'm using Zylanns voxel tools for custom made voxel shaped worlds and extracted it's mesh and used your addon to make it into a nav mesh. So far so good but I'm struggling to get a generalizable setting that allows for slopes  to be walkable without having a stairs form. 

I tried several settings like increasing climb for example but that causes other issues like the mesh trying to climb 90° walls and stuff. So these are my current settings:

```
var navParams = DetourNavigationParameters.new()
var navMeshParams = DetourNavigationMeshParameters.new()
navParams.ticksPerSecond = 60 # How often the navigation is updated per second in its own thread
navParams.maxObstacles = 256 # How many dynamic obstacles can be present at the same time
navMeshParams.cellSize = Vector2(1, 1)
navMeshParams.maxNumAgents = 256
navMeshParams.maxAgentSlope = 80.0
navMeshParams.maxAgentHeight = 2.0
navMeshParams.maxAgentClimb = 1.0
navMeshParams.maxAgentRadius = 0.5
navMeshParams.maxEdgeLength = 2.0
navMeshParams.maxSimplificationError = 1.3
navMeshParams.minNumCellsPerIsland = 8
navMeshParams.minCellSpanCount = 20
navMeshParams.maxVertsPerPoly = 6
navMeshParams.tileSize = 42
navMeshParams.layersPerTile = 8
navMeshParams.detailSampleDistance = 5.0
navMeshParams.detailSampleMaxError = 1.0
navParams.navMeshParameters.append(navMeshParams)
		
var weights :Dictionary = {}
weights[0] = 10.0       # Ground
weights[1] = 5.0        # Road
weights[2] = 10001.0    # Water
weights[3] = 10.0       # Door
weights[4] = 100.0      # Grass
weights[5] = 150.0      # Jump
navigation.setQueryFilter(0, "default", weights)

navigation.initialize(meshInstance, navParams)
```

and these are my settings for adding an agent:

```
func addNavAgent(unit):
	var params = DetourCrowdAgentParameters.new()
	params.position = unit.translation
	params.radius = 0.5
	params.height = 2.0
	params.maxAcceleration = 600.0
	params.maxSpeed = 10.0
	params.filterName = "default"
	params.anticipateTurns = true
	params.optimizeVisibility = true
	params.optimizeTopology = true
	params.avoidObstacles = true
	params.avoidOtherAgents = true
	params.obstacleAvoidance = 1
	params.separationWeight = 1.0
	return navigation.addAgent(params)
```

These kind of stairs kinda work:
![1](https://user-images.githubusercontent.com/49487953/122406200-f1894200-cf80-11eb-8fbd-721543057090.png)

Slopes like these do not work:
![2](https://user-images.githubusercontent.com/49487953/122407399-e5ea4b00-cf81-11eb-9f19-1a34459a129f.png)

Thanks!

**Comment by TheSHEEEP** [comment]
From my understanding (and I'm not a pro on recast/detour internals, so I could be wrong), the `climb` attribute determines the height of **stairs**.  
As such, it isn't really related to slopes. Stairs being climbable at 90° is perfectly normal (just think of real world stairs).  
Maybe I should have renamed it to "stairStepHeight" or sth. like that but I really don't want to cause additional confusion by having different names in godotdetour than detour... it's enough of a mystery as it is ;) 

Your first image looks fine - navmeshes rarely end up fitting everything 100% (especially in cases like stairs) so that is to be expected.

The second one looks like a different problem.

What happens in detour internally to build the navmesh is **NOT** (as it might seem) that there are voxel-like cubes of navigation mesh information. Instead, it's more like a 2D-grid on the ground level, in which some tiles end up having different layers of height (see maxLayers) to store height information with.
And each tile is in turn divided into cells - I really recommend reading the description in https://github.com/TheSHEEEP/godotdetour/blob/master/src/detournavigationmesh.h#L44 as it is my best effort to explain what is going on.

Remember what the debug draw displays in different colors are the tiles, not the cells.

I could imagine the area covered in the second image simply not fitting the sizes you have set for cells & tiles very well.
As such, I'd recommend experimenting with those a bit more.
If that doesn't help, try asking on the recast/actual detour repository.

**Comment by Xeadriel** [comment]
Thanks for the quick answer. 

Yeah I figured that one out with the layers system. It's pretty smart but kinda renders this very difficult as it seems like the navmesh stores flat surfaces and then interconnects them by height depending on the climb value. I never tried changing cell size but played around a lot with tile size to no avail... doubt it'll help but who knows. I'll give it a go. Thanks

**Comment by Xeadriel** [comment]
Yes that worked! The only setting I missed to play with did the trick. Decreasing the cellsize make it work! Awesome thanks.
