### ISSUE TITLE
Unable to get simple agent moveToward script working

### ISSUE THREAD

**Issue by mikeant42** [TheSHEEEP/godotdetour#7]
Godot 3.2.3 stable, ubuntu 18.04

I'd appreciate some pointers on what's going wrong here. The debug navigation mesh is drawing correctly, and the agent has been added correctly, but agent.MoveToward does not update the nav agent's position. The position stays the same. The "player" is just a duplicate of the agent, with the same y axis position just x and z offsets. I figure I'm doing something wrong but I'm not sure what.

'

extends Spatial

const DetourNavigation 	            :NativeScript = preload("res://addons/godotdetour/detournavigation.gdns")
const DetourNavigationParameters	:NativeScript = preload("res://addons/godotdetour/detournavigationparameters.gdns")
const DetourNavigationMesh 	        :NativeScript = preload("res://addons/godotdetour/detournavigationmesh.gdns")
const DetourNavigationMeshParameters    :NativeScript = preload("res://addons/godotdetour/detournavigationmeshparameters.gdns")
const DetourCrowdAgent	            :NativeScript = preload("res://addons/godotdetour/detourcrowdagent.gdns")
const DetourCrowdAgentParameters    :NativeScript = preload("res://addons/godotdetour/detourcrowdagentparameters.gdns")

export var mesh_path := NodePath()
var meshInstance

export var agent_path := NodePath()
var agent

export var player_path := NodePath()
var player

var detourCrowdAgent

var lastUpdateTimestamp
var moveTo

func _ready():
	meshInstance = get_node(mesh_path)
	agent = get_node(agent_path)
	player = get_node(player_path)
	
	# Create the navigation parameters
	var navParams = DetourNavigationParameters.new()
	navParams.ticksPerSecond = 140 # How often the navigation is updated per second in its own thread
	navParams.maxObstacles = 256 # How many dynamic obstacles can be present at the same time
	
	

	# Create the parameters for the "small" navmesh
	var navMeshParamsSmall = DetourNavigationMeshParameters.new()
	navMeshParamsSmall.cellSize = Vector2(0.3, 0.2)
	navMeshParamsSmall.maxNumAgents = 256
	navMeshParamsSmall.maxAgentSlope = 75.0
	navMeshParamsSmall.maxAgentHeight = 2.0
	navMeshParamsSmall.maxAgentClimb = 2 # non-def
	navMeshParamsSmall.maxAgentRadius = 1.0
	navMeshParamsSmall.maxEdgeLength = 12.0
	navMeshParamsSmall.maxSimplificationError = 1.3
	navMeshParamsSmall.minNumCellsPerIsland = 8
	navMeshParamsSmall.minCellSpanCount = 20
	navMeshParamsSmall.maxVertsPerPoly = 6
	navMeshParamsSmall.tileSize = 64
	navMeshParamsSmall.layersPerTile = 4
	navMeshParamsSmall.detailSampleDistance = 6.0
	navMeshParamsSmall.detailSampleMaxError = 1.0
	navParams.navMeshParameters.append(navMeshParamsSmall)

	# Create the parameters for the "large" navmesh
	var navMeshParamsLarge = DetourNavigationMeshParameters.new()
	navMeshParamsLarge.cellSize = Vector2(0.5, 0.35)
	navMeshParamsLarge.maxNumAgents = 128
	navMeshParamsLarge.maxAgentSlope = 75.0
	navMeshParamsLarge.maxAgentHeight = 4.0
	navMeshParamsLarge.maxAgentClimb = 3
	navMeshParamsLarge.maxAgentRadius = 2.5
	navMeshParamsLarge.maxEdgeLength = 12.0
	navMeshParamsLarge.maxSimplificationError = 1.3
	navMeshParamsLarge.minNumCellsPerIsland = 8
	navMeshParamsLarge.minCellSpanCount = 20
	navMeshParamsLarge.maxVertsPerPoly = 6
	navMeshParamsLarge.tileSize = 64
	navMeshParamsLarge.layersPerTile = 4
	navMeshParamsLarge.detailSampleDistance = 6.0
	navMeshParamsLarge.detailSampleMaxError = 1.0
	navParams.navMeshParameters.append(navMeshParamsLarge)

	# Initialize the navigation with the mesh instance and the parameters
	var navigation = DetourNavigation.new()
	navigation.initialize(meshInstance, navParams)
	
	var weights :Dictionary = {}
	weights[0] = 1.0       # Ground
	weights[1] = 1.0        # Road
	weights[2] = 1.0    # Water
	weights[3] = 1.0       # Door
	weights[4] = 1.0      # Grass
	weights[5] = 1.0      # Jump
	navigation.setQueryFilter(0, "default", weights)	
	
	# Create the debug mesh
	# First parameter is the index of the navigation mesh (in case there are multiple)
	# Second parameter is if you want to display the cache boundaries or not (false will only display the navmesh itself, which is likely what most want)
	var debugMeshInstance :MeshInstance = navigation.createDebugMesh(0, false)

	# Add the debug mesh instance a little elevated to avoid z-fighting
	debugMeshInstance.translation = Vector3(0.0, 0.5, 0.0)
	add_child(debugMeshInstance)
	
	
	
	# Create an agent in GodotDetour and remember both
	var params = DetourCrowdAgentParameters.new()
	params.position = agent.translation
	params.radius = 0.2
	params.height = 0.6
	params.maxAcceleration = 6.0
	params.maxSpeed = 3.0
	params.filterName = "default"
	params.anticipateTurns = true
	params.optimizeVisibility = true
	params.optimizeTopology = true
	params.avoidObstacles = true
	params.avoidOtherAgents = true
	params.obstacleAvoidance = 1
	params.separationWeight = 1.0
	detourCrowdAgent = navigation.addAgent(params)
	
	var params2 = DetourCrowdAgentParameters.new()
	params2.position = player.translation
	params2.radius = 0.2
	params2.height = 0.6
	params2.maxAcceleration = 6.0
	params2.maxSpeed = 3.0
	params2.filterName = "default"
	params2.anticipateTurns = true
	params2.optimizeVisibility = true
	params2.optimizeTopology = true
	params2.avoidObstacles = true
	params2.avoidOtherAgents = true
	params2.obstacleAvoidance = 1
	params2.separationWeight = 1.0
	var detourCrowdAgent2 = navigation.addAgent(params2)

	
	navigation.rebuildChangedTiles()

#
func _process(delta):
	var moveTo = player.translation
	#smoveTo.y = agent.translation.y - 0.1
	detourCrowdAgent.moveTowards(moveTo)
	agent.translation = detourCrowdAgent.position
	print(detourCrowdAgent.position)

	lastUpdateTimestamp = OS.get_ticks_msec()

'

**Comment by TheSHEEEP** [comment]
```
func _process(delta):
var moveTo = player.translation
#smoveTo.y = agent.translation.y - 0.1
detourCrowdAgent.moveTowards(moveTo)
agent.translation = detourCrowdAgent.position
print(detourCrowdAgent.position)
```
I see one guaranteed problem and one possible one:

_process is called every single frame in Godot.
moveTowards is not an instantaneous function - it doesn't instantly change the translation right away, but causes the agent to first look for a path towards the goal and then start moving.  
It takes a bit of time - definitely longer than the next line in the script.  
You are essentially using the same position every frame because you never give the agent time to actually move.  
moveTowards should only be called rarely, e.g. as a response to a click, etc.

Another possible problem is that the position you are trying to move to is too far away from the navMesh. Although that should lead to an error on the console.

**Comment by TheSHEEEP** [comment]
I see one guaranteed problem and one possible one:

_process is called every single frame in Godot.
moveTowards is not an instantaneous function - it doesn't change the agent's position right away, but causes the agent to first look for a path towards the goal and then start moving.  
It takes a bit of time - definitely longer than the next line in the script.  
You are essentially using the same position every frame because you never give the agent time to actually move. 
moveTowards should only be called rarely, e.g. as a response to a click, etc.

Another possible problem is that the position you are trying to move to is too far away from the navMesh. Although that should lead to an error on the console.

Also, I don't see any code in there that would actually move the `player`. So what happens in _process would always be the same anyway. Unless `player` was a child of `agent`.

**Comment by mikeant42** [comment]
Thanks for the quick response. I should have mentioned I've tried updating everything inside a timer update function, with long and short wait times. The player right now is just a static object for testing, It's not supposed to be moving now. I attached a demo project - maybe that will help.

Most of the code is copied right from the readme and the demo, I think I must've missed something but I have no idea where.

[testdetourerror.zip](https://github.com/TheSHEEEP/godotdetour/files/6217630/testdetourerror.zip)

**Comment by TheSHEEEP** [comment]
In that code, `moveTo` is never assigned a value. You are passing null to `moveTowards`. I'm somewhat surprised that doesn't lead to a crash. Might just be undefined behavior.

Anyway, the real problem here is that you create DetourNavigation and assign it to a temporary variable - I should have caught that in the initial code, but it didn't even cross my mind to look for that. :laughing: 

GDScript is a reference counted language. If you want variables to stick around, you have to assign them to something that is not just local scope.  
You essentially create a DetourNavigation and it gets shut down immediately the moment the _ready() function is done - you can also see that in the log, the thread ends as soon as it starts.
So when you try to use any navigation, nothing happens because the navigation thread has been shut down already.

**Comment by mikeant42** [comment]
Wow thank you I see the error of my ways lol stupid mistake. I don't usually work with gdscript so I figured it was something dumb Thank you! The moveTo problem was only in the sample code, but your point stands. I just rush through things too fast sometimes.
